Feature
ignatius22/Using-Bootstrap pull request #1
Opened 2020-06-02 02:52 UTC by ignatius22

This is Using Bootstrap project of the Newsweek homepage, there is a full description of the project in the README file, I was unsure how in-depth the Newsweek should go I understood to add some content to the site. I decided to submit the project now for the review.

2020-06-03 00:09 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved, kindly implement the changes mentioned below.

### Happy coding! :computer:

## Lucas Mazo

2020-06-03 00:09 UTC, lucasmazo32 commented on index.html
> +          <li class="input-search">
- [x] This section breaks for large screens. Kindly fix that.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83580577-0627a300-a502-11ea-9504-257ecbd819ad.png) | ![image](https://user-images.githubusercontent.com/57414789/83580563-fc05a480-a501-11ea-93b0-459302a3a3c8.png)

2020-06-03 00:09 UTC, lucasmazo32 commented on index.html
> +              <div class="block-title">TOP STORY</div>
- [x] The top story should go first on small screens.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83580730-661e4980-a502-11ea-997b-4e8066ede066.png) | ![image](https://user-images.githubusercontent.com/57414789/83580750-70d8de80-a502-11ea-836d-c80bec846e13.png)

2020-06-03 00:09 UTC, lucasmazo32 commented on index.html
> +          IN THE MAGAZINE
- [ ] There should be four columns for medium devices in this section.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83581073-61a66080-a503-11ea-9af7-adddf5d7c56b.png) | ![image](https://user-images.githubusercontent.com/57414789/83581052-58b58f00-a503-11ea-9d0b-f6c1f3312fce.png)

2020-06-03 00:09 UTC, lucasmazo32 commented on index.html
> +              EDITOR'S PICK
- [ ] Editor's pick should have two columns for medium devices.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83581141-92869580-a503-11ea-84c1-da44a4359dfa.png) | ![image](https://user-images.githubusercontent.com/57414789/83581123-86023d00-a503-11ea-8de5-d5cd12b3c7f1.png)

2020-06-03 00:09 UTC, lucasmazo32 commented on index.html
> +                  <a href="#">World</a>
- [ ] Kindly check this section for medium devices.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83581263-f01ae200-a503-11ea-9e35-418d3cb85054.png) | ![image](https://user-images.githubusercontent.com/57414789/83581233-e2fdf300-a503-11ea-8e58-91fde2af2ed4.png)

2020-06-03 00:09 UTC, lucasmazo32 commented on index.html
> +                  <div class="block-title1 red">Subscribe</div>
- [ ] This section should have two columns for medium devices. Kindly check that.

Source | Clone
-- | -- 
![image](https://user-images.githubusercontent.com/57414789/83581373-3cfeb880-a504-11ea-9eff-83b2d336c4d7.png) | ![image](https://user-images.githubusercontent.com/57414789/83581359-32dcba00-a504-11ea-83dd-49b03cf367cc.png)

- [ ] Kindly check the layout for small devices.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83581462-7e8f6380-a504-11ea-91f5-3427223a38b9.png) | ![image](https://user-images.githubusercontent.com/57414789/83581446-70d9de00-a504-11ea-94b9-48211894ff8b.png)

2020-06-05 01:17 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, the project is looking good and you did a great job implementing the changes.

For the project to get approved, kindly implement the changes mentioned below.

### Happy coding! :computer:

## Lucas Mazo

2020-06-05 01:17 UTC, lucasmazo32 commented on index.html
> +                      <h3 class="subscribe-block">
- [ ] Kindly add the propper layout for these images like on the source page. Dealing with absolute and relative positioning is a great tool that will help you in the future. You can also check the source page to see how they achieve it.

Source | Clone
-- | --
![image](https://user-images.githubusercontent.com/57414789/83825804-01005a80-a6a0-11ea-86f9-61e1a3a58983.png) | ![image](https://user-images.githubusercontent.com/57414789/83825781-f0e87b00-a69f-11ea-997a-e670f6960b30.png)

2020-06-05 13:00 UTC, santiago-rodrig commented
# Pull Request under Review by @santiago-rodrig (TSE)

2020-06-05 13:19 UTC, santiago-dev96 requested changes
# Changes required 🚫

This project is almost ready for approval, but I think you haven't fully understood how to use CSS positioning.

1. Try to make the subscribe section more similar to the original page

**Original**

<img width="591" alt="Screen Shot 2020-06-05 at 9 15 31 AM" src="https://user-images.githubusercontent.com/43162770/83880571-5757b280-a70d-11ea-84f0-09da3405f8b0.png">

**Yours**

<img width="498" alt="Screen Shot 2020-06-05 at 9 15 02 AM" src="https://user-images.githubusercontent.com/43162770/83880592-6179b100-a70d-11ea-842b-9ca70a168d10.png">

I recommend you to take a read to [this](https://developer.mozilla.org/en-US/docs/Web/CSS/position).

After implementing the changes submit another CRR.

You can find me in slack as **srodrig**, happy coding! :wave:

2020-06-06 00:08 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-06 00:17 UTC, andresporras3423 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
**Hello @ignatius22** 
Amazing job :clap: :clap: you have met all the requirements for this project
Now you are ready to continue with your next challenge :muscle: 
Don't forget to merge with the master branch

Keep going like this,

Oscar Andrés Russi Porras

2020-06-06 06:01 UTC, merged